# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('result_file', models.FilePathField(path='file/kw/result')),
                ('origin_file', models.FileField(upload_to='file/kw/origin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='topseller',
            name='origin_file',
            field=models.FileField(upload_to='file/top/origin'),
        ),
        migrations.AlterField(
            model_name='topseller',
            name='result_file',
            field=models.FilePathField(path='file/top/result'),
        ),
    ]
